# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvaVNeZX-fYJ7FXppjExywSp9Q6rLPfZ
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. Настройка интерфейса
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Параметры системы")

# Константы
N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выбор типа апертуры
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула',
     '8 - Треугольник', '9 - Звездочка', '10 - Две звезды (наслоение)',
     '11 - Три круга (наслоение)')
)

# Сетка координат
coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# Вспомогательная функция для генерации заполненной звезды
def generate_star_mask(X_grid, Y_grid, center_x, center_y, R_out):
    dx, dy = X_grid - center_x, Y_grid - center_y
    R_in = R_out * 0.382

    vertices = []
    for i in range(10):
        radius = R_out if i % 2 == 0 else R_in
        angle = (i * np.pi / 5) - np.pi/2
        vertices.append([center_x + radius * np.cos(angle), center_y + radius * np.sin(angle)])

    vertices = np.array(vertices)
    temp_mask = np.ones((N, N), dtype=bool)

    for i in range(10):
        x_a, y_a = vertices[i]
        x_b, y_b = vertices[(i + 1) % 10]
        temp_mask &= ((x_b - x_a) * (Y_grid - y_a) - (y_b - y_a) * (X_grid - x_a) >= 0)

    return np.where(temp_mask, 1, 0)

# Определяем номер выбора для логики "костыля"
choice_num = choice.split(' ')[0]

# 2. Логика создания масок (апертур)
if choice_num == '1':
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice_num == '2':
    w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.2) / 1000
    mask = np.where((np.abs(Y) < 0.005) & ((np.abs(X - d/2) < w/2) | (np.abs(X + d/2) < w/2)), 1, 0)

elif choice_num == '3':
    wx = st.sidebar.number_input("Ширина по X (мм):", value=0.5) / 1000
    wy = st.sidebar.number_input("Ширина по Y (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < wx/2) & (np.abs(Y) < wy/2), 1, 0)

elif choice_num == '4':
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice_num == '5':
    w1, h1 = 0.0006, 0.0002
    w2, h2 = 0.0002, 0.0006
    m1 = np.where((np.abs(X) < w1/2) & (np.abs(Y) < h1/2), 1, 0)
    m2 = np.where((np.abs(X) < w2/2) & (np.abs(Y) < h2/2), 1, 0)
    mask = np.maximum(m1, m2)

elif choice_num == '6':
    r_c, d_c = 0.0004, 0.0005
    m1 = np.where((X - d_c/2)**2 + Y**2 < r_c**2, 1, 0)
    m2 = np.where((X + d_c/2)**2 + Y**2 < r_c**2, 1, 0)
    mask = np.maximum(m1, m2)

elif choice_num == '7':
    f_text = st.sidebar.text_input("Формула:", value="np.abs(X*Y) < 1e-7")
    try: mask = np.where(eval(f_text), 1, 0)
    except: st.error("Ошибка в формуле")

elif choice_num == '8':
    a = 0.0015
    h = a * np.sqrt(3) / 2
    y_off = h/3
    mask = np.where((Y > -h/2+y_off) & (Y < -np.sqrt(3)*X + h/2+y_off) & (Y < np.sqrt(3)*X + h/2+y_off), 1, 0)

elif choice_num == '9':
    mask = generate_star_mask(X, Y, 0, 0, 0.001)

elif choice_num == '10':
    m1 = generate_star_mask(X, Y, 0.0006, 0, 0.0006)
    m2 = generate_star_mask(X, Y, -0.0006, 0, 0.0006)
    mask = np.maximum(m1, m2)

elif choice_num == '11':
    r_t, d_t = 0.0005, 0.0008
    h_t = d_t * np.sqrt(3) / 2
    m1 = np.where(X**2 + (Y - d_t)**2 < r_t**2, 1, 0)
    m2 = np.where((X - d_t*np.cos(np.pi/6))**2 + (Y + h_t/2)**2 < r_t**2, 1, 0)
    m3 = np.where((X + d_t*np.cos(np.pi/6))**2 + (Y + h_t/2)**2 < r_t**2, 1, 0)
    mask = np.maximum(m1, np.maximum(m2, m3))

# Параметры расстояний
z1 = st.sidebar.number_input("z1 (м):", value=1.0)
z2 = st.sidebar.number_input("z2 (м):", value=1.0)

# 3. Физический расчет
if z1 != 0 and z2 != 0:
    R_eff = 1 / (1/z1 + 1/z2)
    phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))
    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1)
    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # 4. Отрисовка графиков
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500], cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")
    ax1.set_xlabel("x, мм")
    ax1.set_ylabel("y, мм")

    zoom_area = screen_scale_mm * 0.15
    center_idx = N // 2

    # --- ПРИМЕНЕНИЕ КОСТЫЛЯ ДЛЯ ВЕРТИКАЛЬНОСТИ ---
    if choice_num in ['1', '2']:
        # Транспонируем матрицу, чтобы полосы стали вертикальными
        display_intensity = intensity_viz.T
        # Срез берем вертикально, так как картинка повернута
        profile_data = intensity[:, center_idx]
    else:
        # Для остальных фигур (круги, звезды) оставляем как есть
        display_intensity = intensity_viz
        profile_data = intensity[center_idx, :]

    ax2.imshow(display_intensity, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])

    ax2.set_xlim(-zoom_area, zoom_area)
    ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Экран (z2 = {z2} м)")
    ax2.set_xlabel("x, мм")
    ax2.set_ylabel("y, мм")

    st.pyplot(fig)

    # 5. График профиля
    fig_line, ax3 = plt.subplots(figsize=(10, 4))
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)

    max_val = np.max(profile_data)
    norm_profile = profile_data / max_val if max_val > 0 else profile_data

    ax3.plot(x_axis, norm_profile, color='#1f77b4', lw=1.5)
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности (сечение поперек полос)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    st.pyplot(fig_line)
else:
    st.warning("z1 и z2 не могут быть равны нулю.")